version: '3.8'
name: vanilla_php_base

services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm-bullseye
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    command: >
      sh -c "pecl install xdebug-3.2.0 && docker-php-ext-enable xdebug && docker-php-ext-install pdo_mysql && php-fpm"

  mariadb:
    image: mariadb:10
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - type: bind
        source: ./docker/mariadb/database_files
        target: /var/lib/mysql
      - ./docker/mariadb/initialization_scripts:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:fastcgi
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mkdocs
    ports:
      - 8000-8010:8000
    volumes:
      - type: bind
        source: .
        target: /docs