version: '3.8'
name: vanilla_php_base

services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: ${COMPOSE_PROJECT_NAME}-mkdocs
    ports:
      - 8000-8010:8000
    volumes:
      - type: bind
        source: .
        target: /docs