version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm-alpine
    container_name: php
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
