version: '3.8'
name: vanilla_php_base

services:
  nginx:
    image: nginx:alpine
    environment:
      - COMPOSE_PROJECT_NAME
    container_name: nginx-${COMPOSE_PROJECT_NAME}
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm-alpine
    environment:
      - COMPOSE_PROJECT_NAME
    container_name: php-${COMPOSE_PROJECT_NAME}
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    environment:
      - COMPOSE_PROJECT_NAME
    container_name: mkdocs-${COMPOSE_PROJECT_NAME}
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: .
        target: /docs